### ISSUE TITLE
OpenSearch adapter

### ISSUE THREAD

**Issue by t-frog-says-jump** [fox-it/flow.record#100]
Good afternoon. We use dissect/flow.record in our processes and are interested in developing an adapter for OpenSearch. Could you tell me if it is in your plans?

**Comment by yunzheng** [comment]
Hi, thank you for your interest in developing a flow.record adapter for OpenSearch.
Currently, we don't have plans for developing an OpenSearch adapter. However, we welcome community contributions, and if you decide to create a PR, it would be most welcome.
