### ISSUE TITLE
Remove deprecated `ast.Str`, `ast.Bytes` and `ast.NameConstant`.

### ISSUE THREAD

**Issue by Schamper** [fox-it/flow.record#134]
https://github.com/fox-it/flow.record/blob/21cad296ef60113798725e947f5befda034416f1/flow/record/selector.py#L20-L38

**Comment by gardianofthisgalaxy** [comment]
> https://github.com/fox-it/flow.record/blob/21cad296ef60113798725e947f5befda034416f1/flow/record/selector.py#L20-L38

Remove
