### ISSUE TITLE
No module named 'flow.record.adapter.f'

### ISSUE THREAD

**Issue by hozoin** [fox-it/flow.record#38]
When running rdump to read rdump file I get error `ModuleNotFoundError("No module named 'flow.record.adapter.f'")`
I have flow.record 3.7 installed as part of Dissect and Python 3.9.5 on Windows 10.

![image](https://user-images.githubusercontent.com/122273132/211299163-8faf2db6-e1e5-4a16-8c11-e6be8798caee.png)

**Comment by hozoin** [comment]
Thank you for the answer.
The workaround works, although I am creating Kape modules with Dissect, so it is not applicable in my case.
For information, putting the path in quotation marks produces the same error, apostrophes produce another error:` [Errno 22] Invalid argument ` for the path.

**Comment by yunzheng** [comment]
@hozoin Another temporary workaround is to add the prefix `stream://` to your path, eg:

```shell
rdump  stream://F:\vystup\Dissect\chrome.rdump
```

**Comment by yunzheng** [comment]
Related Python issue: https://github.com/python/cpython/issues/86381 (urlparse with a Windows path returns the drive name as the scheme)

**Comment by yunzheng** [comment]
@hozoin Issue is now fixed, you can install the latest pre-release version of `flow.record` using:

```shell
pip install --pre --upgrade flow.record
```

**Comment by Schamper** [comment]
Hi @hozoin, unfortunately it looks like our CI/CD was on the fritz today so no pre-release with this fix was pushed to PyPI, we expect to fix this tomorrow. After that the above instructions should correctly install the latest pre-release with this fix.

**Comment by yunzheng** [comment]
@hozoin should work now.

**Comment by hozoin** [comment]
Hi, yes after updating library again it works and rdump produces output without errors.
