### ISSUE TITLE
rdump csv output has empty CR LF lines

### ISSUE THREAD

**Issue by hozoin** [fox-it/flow.record#42]
Both `rdump <input file> -w csvfile://<output file>` and `rdump <input file> -C > <output file>`  create csv file in which every line ends with CR followed by CR LF. As CR ends line, result is that every second line of csv file is empty line containing only CR LF.

I am using Python 3.9.5 and Windows 10.

**Comment by yunzheng** [comment]
This looks like this issue https://github.com/python/cpython/issues/51447

I think opening the csv file with `newline=""` will fix the issue, will look into it and do some tests

**Comment by hozoin** [comment]
Yes, newline must be specified. https://docs.python.org/3/library/csv.html#id3

**Comment by yunzheng** [comment]
Should be fixed, new build should land on PyPi shortly.
