### ISSUE TITLE
tree-like data structures in flows

### ISSUE THREAD

**Issue by janstarke** [fox-it/flow.record#64]
Dear all,

I'm just fiddling around with using *Apache Avro* (BTW: thanks to your input at DFRWS) and I'm wondering if `flow.record` is able to read hierarchical data structures, e.g. something like this:

```json
{
   "ts":1577092511000,
   "tz":"",
   "ev":"Modified",
   "ed":{
      "file_name":"/Users/Administrator ($FILE_NAME)",
      "user_id":0,
      "group_id":0,
      "mode":"d/drwxrwxrwx",
      "size":92
   }
}
```

The schema looked like this:

```json
{
   "name":"dfir_timeline.TimelineRecord_PosixFile",
   "type":"record",
   "fields":[
      {
         "name":"ts",
         "type":"long"
      },
      {
         "name":"tz",
         "type":"string"
      },
      {
         "name":"ev",
         "type":{
            "name":"PosixFileEvent",
            "type":"enum",
            "symbols":[
               "Modified",
               "Accessed",
               "Changed",
               "Created"
            ]
         }
      },
      {
         "name":"ed",
         "type":{
            "name":"PosixFile",
            "type":"record",
            "fields":[
               {
                  "name":"file_name",
                  "type":"string"
               },
               {
                  "name":"user_id",
                  "type":"long"
               },
               {
                  "name":"group_id",
                  "type":"long"
               },
               {
                  "name":"mode",
                  "type":"string"
               },
               {
                  "name":"size",
                  "type":"long"
               }
            ]
         }
      }
   ]
}
```

If yes, how are these data mapped to the internal `flow.record` format? If not, which schema do you suggest to use, to be maximal compatible to `flow.record`? Especially: How do you map hierarchical data, such as evtx records, to the linear `flow.record` format?

Kind regards, Jan

**Comment by yunzheng** [comment]
Hi @janstarke,

We prefer to work with flat data, however `flow.record` does have support for "Record in Record". For example:

```python
from flow.record import RecordDescriptor, RecordWriter

TimelineRecord = RecordDescriptor(
    "dfir/timeline_posix",
    [
        ("varint", "ts"),
        ("string", "tz"),
        ("string", "ev"),
        ("record", "ed"),
    ],
)
PosixFileRecord = RecordDescriptor(
    "dfir/posix_file",
    [
        ("string", "file_name"),
        ("varint", "user_id"),
        ("varint", "group_id"),
        ("string", "mode"),
        ("filesize", "size"),
    ],
)


with RecordWriter() as writer:
    record = TimelineRecord(ts=1577092511000, tz="", ev="Modified", ed=PosixFileRecord(
        file_name="/Users/Administrator ($FILE_NAME)",
        user_id=0,
        group_id=0,
        mode="d/drwxrwxrwx",
        size=92,
    ))
    writer.write(record)
```

Example output:

```shell
$ python test.py | rdump
<dfir/timeline_posix ts=1577092511000 tz='' ev='Modified' ed=<dfir/posix_file file_name='/Users/Administrator ($FILE_NAME)' user_id=0 group_id=0 mode='d/drwxrwxrwx' size=92.0  B>>

$ python test.py | rdump --line
[reading from stdin]
--[ RECORD 1 ]--
             ts = 1577092511000
             tz = 
             ev = Modified
             ed = <dfir/posix_file file_name='/Users/Administrator ($FILE_NAME)' user_id=0 group_id=0 mode='d/drwxrwxrwx' size=92.0  B>
        _source = None
_classification = None
     _generated = 2023-03-31 11:13:13.709161
       _version = 1

$ python test.py | rdump --json
{
  "ts": 1577092511000,
  "tz": "",
  "ev": "Modified",
  "ed": {
    "file_name": "/Users/Administrator ($FILE_NAME)",
    "user_id": 0,
    "group_id": 0,
    "mode": "d/drwxrwxrwx",
    "size": 92,
    "_source": null,
    "_classification": null,
    "_generated": "2023-03-31T11:13:36.762234",
    "_version": 1
  },
  "_source": null,
  "_classification": null,
  "_generated": "2023-03-31T11:13:36.762432",
  "_version": 1
}
```

However our Avro adapter does not support record in records at this current stage.

About evtx, this is the current RecordDescriptor used for evt: https://github.com/fox-it/dissect.target/blob/e51db2719486031f17b7e5f2e9c34bb6bcfb2916/dissect/target/plugins/os/windows/log/evt.py#L20

The evt recorddescriptors are also dynamically generated based on the fields:
https://github.com/fox-it/dissect.target/blob/e51db2719486031f17b7e5f2e9c34bb6bcfb2916/dissect/target/plugins/os/windows/log/evt.py#L119

**Comment by yunzheng** [comment]
Currently our `avro` reader/writer is very basic and we have probably not explored all the options with it to write a first class adapter. We mainly created it for ingesting it in cloud services such as BigQuery. I would love to know your thoughts and experiences with the Avro format so far.

That said, our main binary serializer/deserializer for `flow.record` uses [msgpack](https://msgpack.org/index.html).

The main code responsible for it is in: https://github.com/fox-it/flow.record/blob/main/flow/record/packer.py
And the record stream reader/writer here: https://github.com/fox-it/flow.record/blob/main/flow/record/stream.py

It's sadly not documented, so the closest is currently those two files. The format is basically a custom file header (`RECORDSTREAM\n`), msgpack for native types, and [msgpack extension types](https://github.com/msgpack/msgpack/blob/master/spec.md#extension-types) for custom types.

**Comment by janstarke** [comment]
This information helped a lot. I was able to write some Rust code which creates a Record that was accepted by `rdump` :muscle: . I think I should document about the format what I know so far :disguised_face: .

Currently, I'm publishing my code at <https://github.com/janstarke/dfir-timeline>. I think, this could be a nice place to write a documentation for me, but no dev user of flow.record would find it here. Do you have a slot in the documentation of flow.record where we could document the format?

**Comment by yunzheng** [comment]
> This information helped a lot. I was able to write some Rust code which creates a Record that was accepted by `rdump` 💪 . I think I should document about the format what I know so far 🥸 .
> 

nice!

> Currently, I'm publishing my code at https://github.com/janstarke/dfir-timeline. I think, this could be a nice place to write a documentation for me, but no dev user of flow.record would find it here. Do you have a slot in the documentation of flow.record where we could document the format?

Certainly! although `flow.record` project only has a README.md at this moment and not it's own documentation.
Most usage examples are on the [dissect-docs](https://github.com/fox-it/dissect-docs/edit/main/docs/source/tools/rdump.rst) repo.

However, we can add a `RECORDSTREAM_FORMAT.md` file to the `flow.record` repository and then reference it from the `README.md` and even the dissect docs. Feel free to make a PR.
